sudo: required

notifications:
  slack: swpp-team8:DU9yzMW01pR6CPdmxs68Zdkv
  email: false

matrix:
  include:
    - language: node_js
      node_js: 10.13
      addons:
        chrome: stable
      cache:
        directories:
          - frontend/node_modules
      env:
          - TEST=frontend
          - CI=true
      before_install:
          - export CHROME_BIN=chromium-browser
          - sh -e /etc/init.d/xvfb start
          - export DISPLAY=:99.0
      install:
          - cd frontend
          - npm install
          - npm install -g @angular/cli
          - npm install -g coveralls
      script:
          - npm test
      after_success:
          - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

    - language: python
      python: 3.6
      cache:
        pip: true
      env:
        - TEST=backend
      install:
        - cd backend
        - pip install django
        - pip install coverage
        - pip install python-coveralls
      script:
        - coverage run --source="./noticetracker" manage.py test
      after_script:
        - coveralls
